routes/web.php
<?php

use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\FeaturedBlogController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name("home");
Route::get('/articles/{blog:slug}', [ArticleController::class, 'show'])->name('articles.show');
Route::get('/category/{category:slug}', [ArticleController::class, 'category'])->name('articles.category');

Route::prefix('dashboard')->middleware(['auth', 'verified'])->group(function(){
    Route::get('/', fn() => view('dashboard'))->name('dashboard');
    Route::resource('categories', CategoryController::class);
    Route::resource('blogs', BlogController::class);
    Route::resource('featured-blogs', FeaturedBlogController::class);
});

require __DIR__ . '/auth.php';

Auth::routes();

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug',
        'description',
        'category_id',
        'image',
        'content',
        'author_id'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function author() {
        return $this->belongsTo(User::class, 'author_id');
    }
}

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\BlogsDataTable;
use App\Http\Controllers\Controller;
use App\Models\Blog;
use App\Http\Requests\StoreBlogRequest;
use App\Http\Requests\UpdateBlogRequest;
use App\Models\Category;
use App\Models\FeaturedBlog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(BlogsDataTable $dataTable, Request $request)
    {
        $categories = Category::all();
        return $dataTable->render('admin.blogs.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::all();

        return view('admin.blogs.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreBlogRequest $request)
    {
        $image = $request->file('image')->store('blogs');
        $slug = Str::slug($request->title);

        Blog::create([
            'title' => $request->title,
            'slug' => $slug,
            'image' => $image,
            'description' => $request->description,
            'content' => $request->content,
            'category_id' => $request->category_id,
            'author_id' => auth()->user()->id,
        ]);

        return redirect()->route('blogs.index')->with('success', 'Blog created successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(Blog $blog)
    {
        return view('admin.blogs.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Blog $blog)
    {
        $categories = Category::all();

        return view('admin.blogs.edit', compact('blog', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateBlogRequest $request, Blog $blog)
    {
        $slug = Str::slug($request->title);
        $image = $request->hasFile('image')
            ? $request->file('image')->store('blogs')
            : $blog->image;

        if ($image && $blog->image) {
            Storage::delete($blog->image);
        }

        $blog->update([
            'title' => $request->title,
            'slug' => $slug,
            'image' => $image,
            'content' => $request->content,
            'description' => $request->description,
            'category_id' => $request->category_id,
        ]);

        return redirect()->route('blogs.index')->with('success', 'Blog updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Blog $blog)
    {
        FeaturedBlog::where('blog_id', $blog->id)->delete();
        $blog->delete();

        return redirect()->route('blogs.index')->with('success', 'Blog deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/blogs/create.blade.php
<x-app-layout>
    <x-slot:title>
        {{ __('Create Blog') }}
    </x-slot:title>

    <x-slot:styles>
        <script src="{{ asset('vendor/ckeditor5/build/ckeditor.js') }}"></script>
    </x-slot:styles>

    <div class="container">
        <div class="card">
            <div class="card-header">Create Blog</div>
            <div class="card-body">
                <form method="POST" action="{{ route('blogs.store') }}" enctype="multipart/form-data">
                    @csrf
                    @method('POST')

                    <div class="row">
                        <div class="col-md-8 mb-3">
                            <label for="title">Title</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title"
                                name="title" value="{{ old('title') }}" required>
                            @error('title')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="col-md-4 mb-3">
                            <div class="form-group">
                                <label for="category_id">Category</label>
                                <select class="form-control @error('category_id') is-invalid @enderror" id="category_id"
                                    name="category_id" required>
                                    <option value="">-- Select Category</option>
                                    @foreach ($categories as $category)
                                    <option value="{{ $category->id }}" {{ old('category_id')==$category->id ?
                                        'selected' : '' }}>
                                        {{ $category->name }}</option>
                                    @endforeach
                                </select>
                                @error('category_id')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-8 mb-3">
                            <label for="description">Description</label>
                            <input type="text" class="form-control @error('description') is-invalid @enderror"
                                id="description" name="description" value="{{ old('description') }}" required>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="image">Image</label>
                            <input type="file" class="form-control @error('image') is-invalid @enderror" id="image"
                                name="image" value="{{ old('image') }}">
                            @error('image')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12 mb-3">
                            <label for="content">Content</label>
                            <textarea class="form-control @error('content') is-invalid @enderror" id="content"
                                name="content">{{ old('content') }}</textarea>

                            @error('content')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>

                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <x-slot:scripts>
        <script>
            ClassicEditor
                            .create( document.querySelector( '#content' ) )
                            .catch( error => {
                                console.error( error );
                            });
        </script>
    </x-slot:scripts>

</x-app-layout>

resources/views/admin/blogs/edit.blade.php
<x-app-layout>

    <x-slot:title>
        {{ __('Edit Blog') }}
    </x-slot:title>

    <x-slot:styles>
        <script src="{{ asset('vendor/ckeditor5/build/ckeditor.js') }}"></script>
    </x-slot:styles>

    <div class="container">
        <div class="card">
            <div class="card-header">Edit Blog</div>
            <div class="card-body">
                <form method="POST" action="{{ route('blogs.update', $blog->id) }}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                    <div class="row">
                        <div class="col-md-8 mb-3">
                            <label for="title">Title</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title"
                                name="title" value="{{ old('title', $blog->title) }}" required>
                            @error('title')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="col-md-4 mb-3">
                            <div class="form-group">
                                <label for="category_id">Category</label>
                                <select class="form-control @error('category_id') is-invalid @enderror" id="category_id"
                                    name="category_id" required>
                                    <option value="">-- Select Category --</option>
                                    @foreach ($categories as $category)
                                    <option value="{{ $category->id }}" {{ old('category_id', $blog->category_id) ==
                                        $category->id ? 'selected' : '' }}>
                                        {{ $category->name }}</option>
                                    @endforeach
                                </select>
                                @error('category_id')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-8 mb-3">
                            <label for="description">Description</label>
                            <input type="text" class="form-control @error('description') is-invalid @enderror"
                                id="description" name="description" value="{{ old('description', $blog->description) }}"
                                required>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="image">Image</label>
                            <input type="file" class="form-control @error('image') is-invalid @enderror" id="image"
                                name="image" value="{{ old('image') }}">
                            @error('image')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12 mb-3">
                            <label for="content">Content</label>
                            <textarea class="form-control @error('content') is-invalid @enderror" id="content"
                                name="content">{{ old('content', $blog->content) }}</textarea>

                            @error('content')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>

                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-warning">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <x-slot:scripts>
        <script>
            ClassicEditor
                            .create( document.querySelector( '#content' ) )
                            .catch( error => {
                                console.error( error );
                            });
        </script>
    </x-slot:scripts>

</x-app-layout>

resources/views/admin/blogs/index.blade.php
<x-app-layout>
    <x-slot:title>
        {{ __('Blogs') }}
    </x-slot:title>

    <x-slot:styles>
        <link href="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-1.13.6/r-2.5.0/datatables.min.css" rel="stylesheet">
    </x-slot:styles>

    <div class="container">
        <div class="card">
            <div class="card-header">Manage Blogs</div>
            <div class="card-body">
                @if (session('success'))
                <div class="alert alert-success">{{ session('success') }}</div>
                @endif

                <div class="d-flex justify-content-end">
                    <a href="{{ route('blogs.create') }}" class="btn btn-primary mb-3">Create Blog</a>
                </div>

                <form action="{{ route('blogs.index') }}" method="GET" class="mb-4" id="form-filter">
                    <div class="row">
                        <div class="col-md-3">
                            <select name="category_id" id="category_id" class="form-control">
                                <option value="" {{ request('category_id') ? '' : 'selected' }}>-- Select Category
                                    @foreach ($categories as $category)
                                <option value="{{ $category->id }}" {{ request('category_id')==$category->id ?
                                    'selected' : '' }}
                                    >{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </form>

                <div class="table-responsive">
                    {{ $dataTable->table() }}
                </div>
            </div>
        </div>
    </div>

    <x-slot:scripts>
        <script src="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-1.13.6/r-2.5.0/datatables.min.js"></script>

        <script>
            $(document).ready(function() {
                $('#form-filter').on('change', function() {
                    $('#form-filter').submit();
                });
            });
        </script>

        @if(request('category_id'))
        {{ $dataTable->ajax(route('blogs.index', ['category_id' => request('category_id')]))->scripts(attributes:
        ['type' => 'module']) }}
        @else
        {{ $dataTable->ajax(route('blogs.index'))->scripts(attributes: ['type' => 'module']) }}
        @endif

    </x-slot:scripts>
</x-app-layout>

resources/views/admin/blogs/show.blade.php
<x-app-layout>

    <x-slot:title>
        {{ __('Detail Blog') }}
    </x-slot:title>

    <x-slot:styles>
        <script src="{{ asset('vendor/ckeditor5/build/ckeditor.js') }}"></script>
    </x-slot:styles>

    <div class="container">
        <div class="card">
            <div class="card-header">Detail Blog</div>
            <div class="card-body">

                <div class="row">
                    <div class="col-md-8 mb-3">
                        <label for="title">Title</label>
                        <input type="text" class="form-control @error('title') is-invalid @enderror" id="title"
                            name="title" value="{{ old('title', $blog->title) }}" disabled>
                        @error('title')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="col-md-4 mb-3">
                        <div class="form-group">
                            <label for="category_id">Category</label>
                            <input type="text" class="form-control @error('category_id') is-invalid @enderror"
                                id="category_id" name="category_id"
                                value="{{ old('category_id', $blog->category->name) }}" disabled>
                            @error('category_id')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="image">Image</label>
                        @if ($blog->image)
                        <br />
                        <img src="{{ asset('storage/' . $blog->image) }}" alt="{{ $blog->title }}" width="100%">
                        @else
                        <span>
                            No image
                        </span>
                        @endif
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label for="content">Content</label>
                        <textarea class="form-control @error('content') is-invalid @enderror" id="content"
                            name="content">{{ old('content', $blog->content) }}</textarea>

                        @error('content')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
            </div>
        </div>
    </div>

    <x-slot:scripts>
        <script>
            ClassicEditor
                        .create( document.querySelector( '#content' ) )
                        .then( editor => {
                            editor.enableReadOnlyMode('editor')
                        })
                        .catch( error => {
                            console.error( error );
                        });
        </script>
    </x-slot:scripts>

</x-app-layout>