routes/web.php
<?php

use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\FeaturedBlogController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name("home");
Route::get('/articles/{blog:slug}', [ArticleController::class, 'show'])->name('articles.show');
Route::get('/category/{category:slug}', [ArticleController::class, 'category'])->name('articles.category');

Route::prefix('dashboard')->middleware(['auth', 'verified'])->group(function(){
    Route::get('/', fn() => view('dashboard'))->name('dashboard');
    Route::resource('categories', CategoryController::class);
    Route::resource('blogs', BlogController::class);
    Route::resource('featured-blogs', FeaturedBlogController::class);
});

require __DIR__ . '/auth.php';

Auth::routes();

app/Models/FeaturedBlog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FeaturedBlog extends Model
{
    use HasFactory;

    protected $fillable = [
        'blog_id',
    ];

    public function blog()
    {
        return $this->belongsTo(Blog::class);
    }
}

app/Http/Controllers/Admin/FeaturedBlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\FeaturedBlogsDataTable;
use App\Http\Controllers\Controller;
use App\Models\FeaturedBlog;
use App\Http\Requests\StoreFeaturedBlogRequest;
use App\Http\Requests\UpdateFeaturedBlogRequest;
use App\Models\Blog;

class FeaturedBlogController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(FeaturedBlogsDataTable $dataTable)
    {
        return $dataTable->render('admin.featured-blogs.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $blogs = Blog::all();

        return view('admin.featured-blogs.create', compact('blogs'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreFeaturedBlogRequest $request)
    {
        FeaturedBlog::create($request->validated());

        return redirect()->route('featured-blogs.index')
            ->with('success', 'Featured blog created successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(FeaturedBlog $featuredBlog)
    {
        $blogs = Blog::all();

        return view('admin.featured-blogs.edit', compact('featuredBlog', 'blogs'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateFeaturedBlogRequest $request, FeaturedBlog $featuredBlog)
    {
        $featuredBlog->update($request->validated());

        return redirect()->route('featured-blogs.index')
            ->with('success', 'Featured blog updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(FeaturedBlog $featuredBlog)
    {
        $featuredBlog->delete();

        return redirect()->route('featured-blogs.index')
            ->with('success', 'Featured blog deleted successfully.');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/featured-blogs/create.blade.php
<x-app-layout>
    <x-slot:title>
        {{ __('Add Featured Blog') }}
    </x-slot:title>

    <div class="container">
        <div class="card">
            <div class="card-header">Add Featured Blog</div>
            <div class="card-body">
                <form method="POST" action="{{ route('featured-blogs.store') }}">
                    @csrf
                    @method('POST')

                    <div class="row">

                        <div class="col-md-4 mb-3">
                            <div class="form-group">
                                <label for="blog_id">Blog</label>
                                <select class="form-control @error('blog_id') is-invalid @enderror" id="blog_id"
                                    name="blog_id">
                                    <option value="">Select Blog</option>
                                    @foreach ($blogs as $blog)
                                    <option value="{{ $blog->id }}" {{ old('blog_id')==$blog->id ? 'selected' : '' }}>{{
                                        $blog->title }}</option>
                                    @endforeach
                                </select>
                                @error('blog_id')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                    </div>

                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin/featured-blogs/edit.blade.php
<x-app-layout>
    <x-slot:title>
        {{ __('Edit Featured Blog') }}
    </x-slot:title>

    <div class="container">
        <div class="card">
            <div class="card-header">Edit Featured Blog</div>
            <div class="card-body">
                <form method="POST" action="{{ route('featured-blogs.update', $featuredBlog->id) }}">
                    @csrf
                    @method('PUT')

                    <div class="row">

                        <div class="col-md-4 mb-3">
                            <div class="form-group">
                                <label for="blog_id">Blog</label>
                                <select class="form-control @error('blog_id') is-invalid @enderror" id="blog_id"
                                    name="blog_id">
                                    <option value="">Select Blog</option>
                                    @foreach ($blogs as $blog)
                                    <option value="{{ $blog->id }}" {{ old('blog_id', $featuredBlog->blog_id) ==
                                        $blog->id ? 'selected' : '' }}>
                                        {{ $blog->title }}</option>
                                    </option>
                                    @endforeach
                                </select>

                                @error('blog_id')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>

                    </div>

                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-warning">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin/featured-blogs/index.blade.php
<x-app-layout>
    <x-slot:title>
        {{ __('Featured Blogs') }}
    </x-slot:title>

    <x-slot:styles>
        <link href="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-1.13.6/r-2.5.0/datatables.min.css" rel="stylesheet">
    </x-slot:styles>

    <div class="container">
        <div class="card">
            <div class="card-header">Manage Featured Blogs</div>
            <div class="card-body">
                @if (session('success'))
                <div class="alert alert-success">{{ session('success') }}</div>
                @endif

                <div class="d-flex justify-content-end">
                    <a href="{{ route('featured-blogs.create') }}" class="btn btn-primary mb-3">Add Featured Blog</a>
                </div>

                <div class="table-responsive">
                    {{ $dataTable->table() }}
                </div>
            </div>
        </div>
    </div>

    <x-slot:scripts>
        <script src="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-1.13.6/r-2.5.0/datatables.min.js"></script>
        
        {{ $dataTable->ajax(route('featured-blogs.index'))->scripts(attributes: ['type' => 'module']) }}
    </x-slot:scripts>
</x-app-layout>